morfeojs/morfeo

README.md
package.json
packages/core/README.md
packages/core/package.json
packages/hooks/README.md
packages/hooks/package.json
packages/jss/README.md
packages/jss/package.json
packages/native/README.md
packages/native/package.json
packages/spec/README.md
packages/spec/package.json
packages/spec/src/types/colors.ts
packages/spec/src/types/radii.ts
packages/styled-components-web/README.md
packages/styled-components-web/package.json
packages/svelte/README.md
packages/svelte/package.json
packages/web/README.md
packages/web/package.json

- @morfeo/core init of documentation
for all the other packages the readme includes only the header

feat: readme files added to all the packages

---

LICENSE
packages/core/README.md
packages/styled-components-web/README.md

- added LICENSE file to ROOT folder

docs: fixes to core and styled components documentations

---

.gitignore
CONTRIBUTING.md
README.md
apps/svelte-sandbox/public/global.css
packages/hooks/src/index.ts
packages/hooks/src/useProps.ts
packages/hooks/src/useStyles.ts
packages/hooks/src/useSubscribe.ts
packages/hooks/src/useTheme.ts
packages/hooks/tests/useProps.test.ts
packages/jss/package.json
packages/jss/src/getStyles.ts
packages/jss/src/index.ts
packages/jss/src/initJSS.ts
packages/jss/src/morfeoJSS.ts
packages/jss/tests/jss.test.ts
packages/react/package.json
packages/web/package.json
packages/web/src/index.ts

- improvements to `@morfeo/hooks`, new hook useProps is added.
- improved `@morfeo/jss` package with a custom JSS plugin to parse the styles
- fixed documentations and comments added to some hooks / utils to provide a better developer experience
- README.md updated

improv: documentations, new hooks and tests

---

.gitignore
apps/benchmarks/package-lock.json
apps/native-sandbox/package-lock.json
apps/svelte-sandbox/package-lock.json
jest.base.js
jest.config.js
lerna.json
package-lock.json
packages/jss/package-lock.json
packages/native/package-lock.json

lcov reporter added to jest coverage reporters to enable codecov
What types of changes does your code introduce to morfeo?

feat: lcov reeporter added

---

packages/spec/README.md
packages/spec/src/properties/transitions.ts
packages/spec/src/properties/zIndices.ts
packages/styled-components-web/src/types.ts

Added documentation for @morfeo/spec package.
Other than documentation for @morfeo/spec, zIndices and transitions files has been swapped since the first was referring properties of the second and vice-versa.

docs: added documentation for @morfeo/spec

---

apps/benchmarks/package.json
package.json
packages/core/package.json
packages/jss/package.json
packages/spec/package.json

fix: benchmarks fixed

---

packages/svelte/README.md
packages/svelte/src/morfeoAction.ts
packages/svelte/tests/morfeo.test.ts

added handling for theme properties in svelte directive.
added tests for the new feature and documentation for the package.

feat(svelte): added support to default properties, docs and tests

---

README.md
docs/docusaurus.config.js
packages/core/README.md
packages/dev-tools/README.md
packages/fonts/README.md
packages/hooks/README.md
packages/jss/README.md
packages/native/README.md
packages/react/README.md
packages/spec/README.md
packages/styled-components-web/README.md
packages/svelte/README.md
packages/web/README.md

Replaced links to website inside README files

feat: website link replaced inside readme files

---

docs/docusaurus.config.js
docs/src/pages/markdown-page.md
docs/src/pages/privacy.md

feat: added privacy policy page

---

docs/docs/Introduction/getting-started.mdx

This reverts commit 193725cdfbeebdb275de8dc777529cb0ef28ffc7.
Reverting because there is already a PR to fix it

Revert "Update getting-started.mdx"

---

docs/package.json
docs/src/theme/Root.js

cookie acceptance added to docusaurus website

feat: cookie acceptance added to docusaurus website

---

apps/web-sandbox/src/components/Button.tsx
packages/core/src/theme/components.ts
packages/styled-components-web/src/styled.ts
packages/styled-components-web/tests/styled.test.tsx

fix: styled-components-web packages

---

apps/web-sandbox/src/theme.ts
packages/web/src/types/core.ts

fix: responsive values typing

---

apps/web-sandbox/src/App.test.tsx
apps/web-sandbox/src/App.tsx
apps/web-sandbox/src/components/Button.test.tsx
apps/web-sandbox/src/components/Button.tsx
apps/web-sandbox/src/components/ThemeToggle.test.tsx
apps/web-sandbox/src/components/ThemeToggle.tsx
apps/web-sandbox/src/components/index.ts
docs/docs/Introduction/easy-to-test.mdx
docs/docs/Introduction/extendible.mdx
docs/docs/Packages/jss.mdx
docs/docs/Packages/native.mdx
docs/docs/theme-specification.mdx
docs/docusaurus.config.js
packages/jss/README.md
packages/native/README.md
packages/web/src/types/core.ts

feat: docs improvements

---

docs/docusaurus.config.js

Enabled algolia docsearch thanks to [DocSearch](https://docsearch.algolia.com/)

feat: enabled algolia docsearch closes #55

---

packages/dev-tools/src/index.js

Fixed `enabledDevTool` function

fix: enable dev tool fixed

---

packages/core/package.json
packages/fonts/package.json
packages/jss/package.json
packages/spec/package.json
packages/web/package.json

Incuded commonjs build to increase compatibility of morfeo in al environments

feat: commonjs build included

---

packages/core/src/parsers/shadows.ts
packages/core/tests/parsers/shadows.test.ts
packages/preset-default/src/base/radii.ts
packages/preset-default/src/base/shadows.ts
packages/spec/src/types/shadows.ts

fix: shadow parser fix & improvements

---

docs/docs/Features/cli.mdx
docs/docs/Packages/cli.mdx
docs/package.json
packages/cli/README.md
packages/cli/src/utils/buildTheme.ts
packages/cli/src/utils/getClassesCSS.ts
packages/cli/src/utils/getComponentsCSS.ts
packages/cli/src/utils/parseSlice.ts
packages/cli/tests/commands/build.test.ts

Improved build command of the CLI

feat: cli improvements

---

packages/core/src/morfeo.ts
packages/core/src/types.ts

Creation of global variable with the morfeo singleton, it will be useful for the future version of the dev-tool

feat: morfeo instance singleton

---

apps/benchmarks/src/core/componentStyle.js
apps/benchmarks/src/core/singleComplexProperty.js
apps/benchmarks/src/core/utils.js
apps/benchmarks/src/jss/utils.js
apps/native-sandbox/metro.config.js
packages/cli/src/utils/parseSlice.ts
packages/hooks/tests/useProps.test.ts
packages/preset-default/src/base/baseTheme.ts

Fixes suggested by Deep scan to improve code quality.

feat: deep scan improvements

---

packages/spec/src/types/components.ts

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
What types of changes does your code introduce to morfeo?
_Put an `x` in the boxes that apply_
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

feat: closes #79

---

package-lock.json
package.json
scripts/bootstrap-app.ts
scripts/symlink-packages.ts
scripts/utils/constants.ts
scripts/utils/filterInternalDependencies.ts
scripts/utils/getLernaJson.ts
scripts/utils/getPackages.ts
scripts/utils/index.ts
scripts/version.ts

Post-Versioning script and all scripts converted in Typescript
closes #90  
Read issue #90

feat: post-versioning script

---

docs/docs/ThemeSpecification/borderStyles.mdx
docs/docs/ThemeSpecification/borderWidths.mdx
docs/docs/ThemeSpecification/borders.mdx
docs/docs/ThemeSpecification/breakpoints.mdx
docs/docs/ThemeSpecification/colors.mdx
docs/docs/ThemeSpecification/components.mdx
docs/docs/ThemeSpecification/fontSizes.mdx
docs/docs/ThemeSpecification/fontWeights.mdx
docs/docs/ThemeSpecification/fonts.mdx
docs/docs/ThemeSpecification/gradients.mdx
docs/docs/ThemeSpecification/letterSpacings.mdx
docs/docs/ThemeSpecification/lineHeights.mdx
docs/docs/ThemeSpecification/opacities.mdx
docs/docs/ThemeSpecification/radii.mdx
docs/docs/ThemeSpecification/shadows.mdx
docs/docs/ThemeSpecification/sizes.mdx
docs/docs/ThemeSpecification/spacings.mdx
docs/docs/ThemeSpecification/transitions.mdx
docs/docs/ThemeSpecification/zIndices.mdx
docs/docusaurus.config.js
docs/package.json
docs/src/components/CodeSnippet/CodeSnippet.js
docs/src/components/CodeSnippet/CodeSnippet.module.css
docs/src/components/CodeSnippet/index.js
docs/src/components/HomepageFeatures/HomepageFeatures.js
docs/src/components/HomepageFeatures/HomepageFeatures.module.css
docs/src/theme/Root.js

- fixed text under properties section in all theme slices documentation pages
- removed pwa plugin since it was causing issues on mobile
- refactor of CodeSnippet component

fix: documentation website fixes

---

devtool/public/manifest.firefox.json
devtool/public/manifest.json
package.json
scripts/version-devtool.ts

Version of the web extension upgraded

feat: web extension version upgraded

---

CHANGELOG.md
devtool/package.json
devtool/public/manifest.firefox.json
devtool/public/manifest.json
lerna.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/dev-tools/CHANGELOG.md
packages/dev-tools/package.json
packages/fonts/CHANGELOG.md
packages/fonts/package.json
packages/hooks/CHANGELOG.md
packages/hooks/package.json
packages/jss/CHANGELOG.md
packages/jss/package.json
packages/native/CHANGELOG.md
packages/native/package.json
packages/preset-default/CHANGELOG.md
packages/preset-default/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/spec/CHANGELOG.md
packages/spec/package.json
packages/svelte/CHANGELOG.md
packages/svelte/package.json
packages/web/CHANGELOG.md
packages/web/package.json

chore: version 0.6.0

---

.github/workflows/build-web-extension.yml
package.json

Added workflow to ensure the web extension is properly building for each pull request
> If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

feat: added workflow to ensure the web-extension is building

---

docs/package.json
docs/yarn.lock

Revert "fix(deps): update dependency @mdx-js/react to v2"

---

.github/workflows/deploy-web-extension.yml
.github/workflows/publish.yml
devtool/.gitignore
devtool/package.json
devtool/scripts/deploy.js
devtool/scripts/deploy.mjs
devtool/scripts/zip.js
devtool/yarn.lock
package.json

Added:
- 2 scripts to zip & publish the browser extension
- a new Git Hub workflow to automate this process for each new release
Closes #201 
---

chore(devtool): #201 automate web extension deployment

---

docs/src/theme/Root.js

removed unused import from the documentation website
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
> If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

fix(docs): removed unused import

---

packages/spec/src/types/borders.ts
packages/spec/src/types/colors.ts
packages/spec/src/types/fonts.ts
packages/spec/src/types/gradients.ts
packages/spec/src/types/opacities.ts
packages/spec/src/types/radii.ts
packages/spec/src/types/shadows.ts
packages/spec/src/types/sizes.ts
packages/spec/src/types/spacings.ts
packages/spec/src/types/transitions.ts
packages/spec/src/types/zIndices.ts
packages/web/src/types/pseudos.ts

> Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
> What types of changes does your code introduce to morfeo?
> _Put an `x` in the boxes that apply_
> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
> If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

chore: prettier

---

.github/PULL_REQUEST_TEMPLATE.md
packages/babel-plugin/src/visitor.ts
packages/babel-plugin/tests/plugin.test.ts
packages/babel-plugin/tests/visitor.test.ts
packages/core/src/morfeo.ts
packages/core/tests/morfeo.test.ts
packages/css/LICENSE
packages/css/README.md
packages/css/jest.config.js
packages/css/package.json
packages/css/src/createUseClasses.ts
packages/css/src/index.ts
packages/css/tests/createUseClasses.test.ts
packages/css/tsconfig.json
packages/webpack/package.json
packages/webpack/src/loader.ts
packages/webpack/tests/__mocks__/webpack-virtual-modules.js
packages/webpack/tests/loader.test.ts

```tsx
import { createUseClasses } from "@morfeo/css"
const useClasses = createUseClasses({
container: {
p: 'm',
bg: 'background',
corner: 's',
},
title: {
fontSize: 'l',
mb: 'm'
},
});
function MyComponent() {
const classes = useClasses();
return (
<div className={classes.container}>
<h1 className={classes.title}>Hello world!</h1>
</div>
)
}
```
This will be replaced at **build-time** into something like:
```tsx
import { createUseClasses } from "@morfeo/css"
const useClasses = () => ({
container: 'p-m bg-background corner-s',
title: 'fontSize-l mb-m',
});
function MyComponent() {
const classes = useClasses();
return (
<div className={classes.container}>
<h1 className={classes.title}>Hello world!</h1>
</div>
)
}
```
And also the related `css` will be generated:
```css
.p-m {
padding: …
```

feat: introduced @morfeo/css package

---

packages/core/src/parsers/createParsers.ts
packages/core/tests/morfeo.test.ts
packages/core/tests/parsers/responsive.test.ts
packages/spec/src/types/style.ts
packages/web/src/parsers/gradients.ts
packages/web/tests/gradient.test.ts

feat(core): #710 handling for raw values

---

examples/next/src/components/Button.morfeo.ts
examples/next/src/components/Card.tsx
examples/next/src/components/Link.tsx
examples/next/src/components/Main.tsx
examples/react/src/components/Card.tsx
packages/babel-plugin/src/utils/css.ts
packages/babel-plugin/src/utils/dynamicClasses.ts
packages/babel-plugin/src/utils/getStyleFromPath.ts
packages/babel-plugin/src/utils/splitStyles.ts
packages/babel-plugin/src/visitor.ts
packages/babel-plugin/src/visitors/createUseStyle.ts
packages/babel-plugin/src/visitors/css.ts
packages/babel-plugin/tests/splitStyles.test.ts
packages/babel-plugin/tests/visitor.test.ts
packages/compiler/src/plugin.ts
packages/compiler/src/transformer.ts
packages/compiler/src/utils.ts
packages/compiler/tests/plugin.spec.ts
packages/compiler/tests/transformer.test.ts
packages/compiler/tests/utils.spec.ts
packages/css/README.md
packages/css/src/createUseStyle.ts
packages/css/src/css.ts
packages/css/src/index.ts
packages/css/src/types.ts
packages/css/tests/css.test.ts
packages/preset-default/src/base/components/Forms/Button.ts
packages/preset-default/src/base/components/Typography.ts
packages/preset-default/src/index.ts

Introduced a new build time API called `css`:
```tsx
import { css } from "@morfeo/css";
const classes = css({
button: {
componentName: 'Button',
variant: 'primary'
},
});
function Button() {
return <button className={classes.button} />
}
```

feat(css): introduced css function

---

.github/workflows/publish.yml
package.json

fix(ci): publish script

---

.changeset/heavy-clocks-laugh.md
packages/core/src/parsers/sizes.ts
packages/core/tests/parsers/sizes.test.ts
packages/spec/src/properties/sizes.ts

Added a short version of width and height. Also, the other attributes based on these attributes have been added with the short version: 
-  `minW`,
- `maxW`,
- `minH`,
- `maxH`
closes #723

feat(core): added short version of width and height

---

.github/workflows/build-web-extension.yml
.github/workflows/codecov.yml

Limit workflows run only on pull requests

chore(ci): workflows only on PRs

---

.github/workflows/publish.yml
package.json

Change `version` script name to not conflict with `pnpm version`

chore: fix changesets

---

.changeset/little-toys-jam.md
package.json
pnpm-lock.yaml

chore(ci): fix publish command

---

.github/actions/setup-environment/action.yml
pnpm-lock.yaml

Fixed `pnpm` and `node` version in setup action

fix(ci): fixed pnpm and node version in the setup action

---

examples/nextra/src/components/HowItWorks/HowItWorks.tsx
examples/nextra/src/components/HowItWorks/MobileSteps.tsx
examples/nextra/src/components/HowItWorks/Step.tsx
examples/nextra/src/components/HowItWorks/Steps.tsx
packages/core/src/theme/createTheme.ts

Completed HowItWorks section
WIP #707
Added all components to complete the HowItWorks section. Once the `CodeHighlighter` component is ready, we need to add the relative codes to the `preview` div. At the moment, that element contains a string.  
> Desktop
> Smartphone

feat(docs): Completed HowItWorks section

---

.github/actions/setup-environment/action.yml
examples/next/package.json
examples/nextra/package.json
package.json
pnpm-lock.yaml

Updated `next`, `nextra` and `pnpm`

chore(deps): updated next, nextra and pnpm

---

.github/actions/setup-environment/action.yml
package.json

Bumped `pnpm` version in `package.json` and github actions.

chore(deps): pnpm version bumped

---

examples/next/package.json
examples/nextra/package.json
examples/nextra/src/components/BundleSize/BundleSize.tsx
examples/nextra/src/components/FadeInBox/FadeInBox.tsx
examples/nextra/src/components/HowItWorks/CSS.mdx
examples/nextra/src/components/HowItWorks/HowItWorks.tsx
examples/nextra/src/components/PlaygroundSection/PlaygroundSection.tsx
examples/nextra/src/components/WebExtensionSection/WebExtensionSection.tsx
examples/nextra/src/components/WebExtensionSection/WebExtensionStep.tsx
pnpm-lock.yaml

docs: new website improvements

---

.github/actions/setup-environment/action.yml
package.json

chroe(version): updated pnpm

---

docs/package.json
examples/next/package.json
examples/react/package.json
pnpm-lock.yaml
web-extension/package.json

- removed redundant dependencies
- unified `nextjs` versions

chore: removed unecessary or redundant dependencies

---

packages/compiler/src/collector.ts
packages/compiler/src/logger.ts
packages/web/src/defaultTheme/index.ts
packages/web/src/morfeo.ts
packages/web/src/resolvers/multiThemeProperty.ts
packages/web/src/types/core.ts
packages/web/src/types/index.ts
packages/web/src/types/schemas.ts
packages/web/src/types/schemes.ts
packages/web/src/utils/extractCssVariables.ts
packages/web/src/utils/multiTheming.ts

Enables the customization of color schemes:
```typescript
{
colorSchemes: {
light: 'data-theme="light"',,
dark: 'data-theme="dark"',
custom: 'data-theme="custom"'
}
}
```
Closes #571

feat: #571

---

package.json
pnpm-lock.yaml

Removed unused packages `rimraf`

chore(deps): removed rimraf

---

docs/package.json
examples/next/package.json
pnpm-lock.yaml

#YOLO
No new API means I can update, right?

YOLO: update next to version 14
